source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "kramdown-parser-gfm"
gem "webrick"
gem "csv"
gem "base64"
gem "bigdecimal"
gem "jekyll-feed"
gem "jekyll-github-metadata"
